// 휴심컬러 컬러+도형 심리카드 데이터
// 9가지 컬러 × 7가지 도형 = 63장 카드

export type ShapeType = 'circle' | 'triangle' | 'inverted_triangle' | 'square' | 'diamond' | 'pentagon' | 'hexagon';
export type CardColorType = 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'navy' | 'purple' | 'white' | 'black';

export interface CardData {
  id: string;                    // e.g. "red_circle"
  color: CardColorType;
  shape: ShapeType;
  colorKor: string;              // 레드, 오렌지 ...
  shapeKor: string;              // 동그라미, 삼각형 ...
  colorHex: string;              // 카드 배경색
  shapeSymbol: string;           // 도형 이모지 또는 SVG path 식별자
  // 해석 데이터
  energyTitle: string;           // 조합 에너지 제목 (예: "안정과 조화")
  psychologyFlow: string;        // 현재 심리 흐름
  personalityFlow: string;       // 성격 흐름
  emotionPattern: string;        // 감정 패턴
  strengths: string[];           // 장점 키워드
  complementColors: string[];    // 보완 컬러
  recoveryDirection: string;     // 회복 방향
  coachingMessage: string;       // 코칭 메시지
}

// 컬러 정보
export const CARD_COLORS: Record<CardColorType, { kor: string; hex: string; textColor: string }> = {
  red:    { kor: '레드',   hex: '#E53935', textColor: '#FFFFFF' },
  orange: { kor: '오렌지', hex: '#FB8C00', textColor: '#FFFFFF' },
  yellow: { kor: '옐로우', hex: '#FDD835', textColor: '#3A2A00' },
  green:  { kor: '그린',   hex: '#43A047', textColor: '#FFFFFF' },
  blue:   { kor: '블루',   hex: '#1E88E5', textColor: '#FFFFFF' },
  navy:   { kor: '네이비', hex: '#283593', textColor: '#FFFFFF' },
  purple: { kor: '퍼플',   hex: '#8E24AA', textColor: '#FFFFFF' },
  white:  { kor: '화이트', hex: '#F5F5F0', textColor: '#2A2A2A' },
  black:  { kor: '블랙',   hex: '#212121', textColor: '#FFFFFF' },
};

// 도형 정보
export const CARD_SHAPES: Record<ShapeType, { kor: string; symbol: string }> = {
  circle:           { kor: '동그라미',  symbol: '○' },
  triangle:         { kor: '삼각형',   symbol: '△' },
  inverted_triangle:{ kor: '역삼각형', symbol: '▽' },
  square:           { kor: '네모',     symbol: '□' },
  diamond:          { kor: '마름모',   symbol: '◇' },
  pentagon:         { kor: '오각형',   symbol: '⬠' },
  hexagon:          { kor: '육각형',   symbol: '⬡' },
};

// 63장 카드 데이터
export const CARD_DATA: CardData[] = [

  // ─────────────────────────────────────────
  // 레드 (RED) - 7장
  // ─────────────────────────────────────────
  {
    id: 'red_circle', color: 'red', shape: 'circle',
    colorKor: '레드', shapeKor: '동그라미', colorHex: '#E53935', shapeSymbol: '○',
    energyTitle: '열정과 포용',
    psychologyFlow: '강한 생명력과 따뜻한 포용 에너지가 함께 흐르고 있습니다. 주변을 이끌고 싶은 마음과 함께 관계 안에서 안정을 찾으려는 흐름이 이어지고 있습니다.',
    personalityFlow: '에너지가 넘치고 사람들과의 연결을 소중히 여기는 성향입니다. 열정적으로 시작하지만 관계 속에서 조화를 중요하게 생각하는 흐름이 있습니다.',
    emotionPattern: '감정이 빠르게 올라오고 빠르게 표현되는 편입니다. 감정을 억누르기보다 자연스럽게 흘려보내는 방향이 회복에 도움이 됩니다.',
    strengths: ['강한 생명력', '따뜻한 포용력', '관계 중심 에너지', '추진력'],
    complementColors: ['블루', '그린'],
    recoveryDirection: '감정의 속도를 조금 늦추고, 내면의 따뜻함을 자신에게도 향하게 해보세요.',
    coachingMessage: '당신의 열정은 주변을 살리는 에너지입니다.\n그 에너지를 먼저 자신에게 선물해보세요.',
  },
  {
    id: 'red_triangle', color: 'red', shape: 'triangle',
    colorKor: '레드', shapeKor: '삼각형', colorHex: '#E53935', shapeSymbol: '△',
    energyTitle: '강한 추진과 성장 의지',
    psychologyFlow: '목표를 향해 강하게 나아가려는 에너지가 활성화되어 있습니다. 지금 이 시기는 무언가를 이루고 싶은 강한 의지가 내면에서 올라오는 흐름입니다.',
    personalityFlow: '도전을 두려워하지 않고 앞으로 나아가는 성향입니다. 경쟁적인 상황에서도 자신의 방향을 잃지 않으려는 흐름이 있습니다.',
    emotionPattern: '감정이 행동으로 빠르게 연결되는 패턴입니다. 때로는 잠시 멈추고 감정을 정리하는 시간이 더 큰 힘이 됩니다.',
    strengths: ['강한 추진력', '목표 지향성', '도전 정신', '리더십'],
    complementColors: ['네이비', '그린'],
    recoveryDirection: '강한 에너지를 방향성 있게 사용하고, 중간중간 내면을 점검하는 시간을 가져보세요.',
    coachingMessage: '앞으로 나아가는 힘이 있습니다.\n방향을 잘 잡으면 그 힘이 더 빛납니다.',
  },
  {
    id: 'red_inverted_triangle', color: 'red', shape: 'inverted_triangle',
    colorKor: '레드', shapeKor: '역삼각형', colorHex: '#E53935', shapeSymbol: '▽',
    energyTitle: '감정 방출과 내면 재정렬',
    psychologyFlow: '강한 감정 에너지가 내면에서 아래로 흘러내리려는 흐름입니다. 오랫동안 억눌려 있던 감정이 표면으로 올라오려는 시기일 수 있습니다.',
    personalityFlow: '감정이 풍부하고 내면의 소리에 민감한 성향입니다. 감정을 솔직하게 표현할 때 에너지가 회복되는 흐름이 있습니다.',
    emotionPattern: '감정이 쌓이다가 한꺼번에 표출되는 패턴이 있습니다. 작은 감정들을 조금씩 표현하는 연습이 도움이 됩니다.',
    strengths: ['감정 표현력', '내면 감수성', '솔직함', '회복 탄력성'],
    complementColors: ['블루', '화이트'],
    recoveryDirection: '억눌린 감정을 안전하게 꺼내는 공간을 만들어보세요. 글쓰기나 대화가 도움이 됩니다.',
    coachingMessage: '감정을 꺼내는 것은 용기 있는 일입니다.\n그 감정들이 당신을 더 깊이 이해하게 해줍니다.',
  },
  {
    id: 'red_square', color: 'red', shape: 'square',
    colorKor: '레드', shapeKor: '네모', colorHex: '#E53935', shapeSymbol: '□',
    energyTitle: '열정과 안정의 균형',
    psychologyFlow: '강한 에너지를 안정적인 구조 안에서 사용하려는 흐름입니다. 열정적이지만 동시에 체계와 질서를 원하는 마음이 함께 있습니다.',
    personalityFlow: '열정적이면서도 실용적인 성향입니다. 계획을 세우고 실행하는 것에서 만족감을 얻는 흐름이 있습니다.',
    emotionPattern: '감정과 이성 사이에서 균형을 찾으려는 패턴입니다. 감정을 인정하면서도 현실적인 방향으로 연결하는 것이 자연스럽습니다.',
    strengths: ['실행력', '체계적 사고', '열정', '안정 추구'],
    complementColors: ['그린', '블루'],
    recoveryDirection: '열정을 구체적인 계획으로 연결해보세요. 작은 성취가 큰 회복이 됩니다.',
    coachingMessage: '열정과 안정은 함께 갈 수 있습니다.\n하나씩 쌓아가는 당신의 흐름을 믿어보세요.',
  },
  {
    id: 'red_diamond', color: 'red', shape: 'diamond',
    colorKor: '레드', shapeKor: '마름모', colorHex: '#E53935', shapeSymbol: '◇',
    energyTitle: '변화 속 열정',
    psychologyFlow: '변화와 새로움을 향한 강한 에너지가 흐르고 있습니다. 현재 상황에서 새로운 방향을 찾으려는 내면의 움직임이 활발합니다.',
    personalityFlow: '유연하고 적응력이 강한 성향입니다. 변화를 두려워하기보다 기회로 바라보는 흐름이 있습니다.',
    emotionPattern: '새로운 자극에 빠르게 반응하는 패턴입니다. 변화 속에서도 내면의 중심을 잡는 연습이 도움이 됩니다.',
    strengths: ['적응력', '창의성', '변화 수용', '열정'],
    complementColors: ['네이비', '그린'],
    recoveryDirection: '변화의 흐름 속에서 자신의 중심 가치를 확인해보세요.',
    coachingMessage: '변화는 당신에게 새로운 가능성을 열어줍니다.\n그 흐름 안에서 자신을 잃지 마세요.',
  },
  {
    id: 'red_pentagon', color: 'red', shape: 'pentagon',
    colorKor: '레드', shapeKor: '오각형', colorHex: '#E53935', shapeSymbol: '⬠',
    energyTitle: '다방면 열정 에너지',
    psychologyFlow: '여러 방향으로 에너지가 뻗어나가는 흐름입니다. 다양한 관심사와 열정이 동시에 활성화되어 있는 시기입니다.',
    personalityFlow: '다재다능하고 호기심이 많은 성향입니다. 여러 분야에서 동시에 에너지를 발휘하는 흐름이 있습니다.',
    emotionPattern: '에너지가 분산되면서 피로감을 느낄 수 있는 패턴입니다. 우선순위를 정하고 집중하는 시간이 회복에 도움이 됩니다.',
    strengths: ['다재다능', '호기심', '열정', '다양성'],
    complementColors: ['네이비', '화이트'],
    recoveryDirection: '다양한 관심사 중 지금 가장 중요한 하나에 집중해보세요.',
    coachingMessage: '당신의 다양한 에너지는 큰 자산입니다.\n지금은 하나에 집중하는 시간입니다.',
  },
  {
    id: 'red_hexagon', color: 'red', shape: 'hexagon',
    colorKor: '레드', shapeKor: '육각형', colorHex: '#E53935', shapeSymbol: '⬡',
    energyTitle: '열정과 연결의 확장',
    psychologyFlow: '강한 에너지가 여러 방향으로 연결되며 확장되는 흐름입니다. 관계와 네트워크를 통해 에너지를 발휘하려는 움직임이 있습니다.',
    personalityFlow: '사람들과의 연결을 통해 에너지를 얻는 성향입니다. 협력과 공동 작업에서 강한 열정을 발휘하는 흐름이 있습니다.',
    emotionPattern: '관계 속에서 감정이 활성화되는 패턴입니다. 건강한 경계를 유지하면서 연결하는 것이 중요합니다.',
    strengths: ['연결력', '협력', '열정', '네트워킹'],
    complementColors: ['블루', '화이트'],
    recoveryDirection: '관계 속에서 자신의 에너지를 지키는 경계를 만들어보세요.',
    coachingMessage: '연결하는 당신의 에너지가 주변을 풍요롭게 합니다.\n자신도 그 풍요 안에 포함시켜 주세요.',
  },

  // ─────────────────────────────────────────
  // 오렌지 (ORANGE) - 7장
  // ─────────────────────────────────────────
  {
    id: 'orange_circle', color: 'orange', shape: 'circle',
    colorKor: '오렌지', shapeKor: '동그라미', colorHex: '#FB8C00', shapeSymbol: '○',
    energyTitle: '따뜻한 활력과 포용',
    psychologyFlow: '따뜻하고 활기찬 에너지가 주변을 감싸는 흐름입니다. 사람들과의 연결 속에서 기쁨과 활력을 찾으려는 마음이 흐르고 있습니다.',
    personalityFlow: '밝고 사교적인 성향으로 주변에 온기를 전하는 흐름이 있습니다. 관계 속에서 자연스럽게 에너지가 활성화됩니다.',
    emotionPattern: '감정을 밝게 표현하고 긍정적인 방향으로 전환하는 패턴입니다. 때로는 내면의 조용한 시간도 필요합니다.',
    strengths: ['따뜻함', '사교성', '활력', '긍정 에너지'],
    complementColors: ['블루', '퍼플'],
    recoveryDirection: '밝은 에너지를 유지하면서도 내면을 돌보는 조용한 시간을 가져보세요.',
    coachingMessage: '당신의 따뜻함이 주변을 밝힙니다.\n그 빛을 자신에게도 비춰주세요.',
  },
  {
    id: 'orange_triangle', color: 'orange', shape: 'triangle',
    colorKor: '오렌지', shapeKor: '삼각형', colorHex: '#FB8C00', shapeSymbol: '△',
    energyTitle: '창의적 성장 에너지',
    psychologyFlow: '새로운 아이디어와 창의적인 에너지가 위로 솟구치는 흐름입니다. 무언가를 시작하고 만들어가려는 의욕이 활성화되어 있습니다.',
    personalityFlow: '창의적이고 표현력이 풍부한 성향입니다. 새로운 것을 시도하는 것에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '아이디어가 넘치지만 실행으로 이어지는 과정에서 에너지가 분산될 수 있습니다. 하나씩 완성해가는 경험이 도움이 됩니다.',
    strengths: ['창의성', '표현력', '의욕', '새로움 추구'],
    complementColors: ['네이비', '그린'],
    recoveryDirection: '창의적인 에너지를 하나의 프로젝트에 집중하여 완성하는 경험을 해보세요.',
    coachingMessage: '당신의 창의성은 세상을 더 풍요롭게 합니다.\n하나씩 완성해가는 기쁨을 느껴보세요.',
  },
  {
    id: 'orange_inverted_triangle', color: 'orange', shape: 'inverted_triangle',
    colorKor: '오렌지', shapeKor: '역삼각형', colorHex: '#FB8C00', shapeSymbol: '▽',
    energyTitle: '감정 표현과 내면 회복',
    psychologyFlow: '활발한 감정 에너지가 내면으로 흘러들어가 정리되는 흐름입니다. 표현하고 싶은 감정들이 내면에서 재정렬되는 시기입니다.',
    personalityFlow: '감정이 풍부하고 표현적인 성향이지만, 때로는 내면으로 깊이 들어가는 시간도 필요한 흐름이 있습니다.',
    emotionPattern: '감정의 기복이 있지만 빠르게 회복하는 패턴입니다. 감정을 표현한 후 내면을 정리하는 시간이 도움이 됩니다.',
    strengths: ['감정 표현력', '회복력', '공감 능력', '활력'],
    complementColors: ['블루', '그린'],
    recoveryDirection: '감정을 충분히 표현한 후, 조용히 내면을 정리하는 시간을 가져보세요.',
    coachingMessage: '감정을 표현하는 것과 내면을 돌보는 것,\n둘 다 당신에게 필요한 흐름입니다.',
  },
  {
    id: 'orange_square', color: 'orange', shape: 'square',
    colorKor: '오렌지', shapeKor: '네모', colorHex: '#FB8C00', shapeSymbol: '□',
    energyTitle: '활력과 실용성',
    psychologyFlow: '활기찬 에너지를 실용적인 방향으로 사용하려는 흐름입니다. 즐겁게 일하고 성취감을 느끼려는 마음이 흐르고 있습니다.',
    personalityFlow: '활발하면서도 실용적인 성향입니다. 즐거움과 효율성을 동시에 추구하는 흐름이 있습니다.',
    emotionPattern: '일과 즐거움을 연결하려는 패턴입니다. 지나치게 바쁜 상태가 지속되면 활력이 떨어질 수 있어 쉬는 시간도 중요합니다.',
    strengths: ['활력', '실용성', '즐거움 추구', '실행력'],
    complementColors: ['블루', '화이트'],
    recoveryDirection: '즐거움을 잃지 않으면서도 충분한 휴식을 통해 에너지를 재충전해보세요.',
    coachingMessage: '일하는 것도 쉬는 것도 모두 당신의 에너지입니다.\n균형 속에서 더 오래 빛날 수 있습니다.',
  },
  {
    id: 'orange_diamond', color: 'orange', shape: 'diamond',
    colorKor: '오렌지', shapeKor: '마름모', colorHex: '#FB8C00', shapeSymbol: '◇',
    energyTitle: '유연한 활력',
    psychologyFlow: '상황에 따라 유연하게 에너지를 조절하는 흐름입니다. 변화 속에서도 활력을 잃지 않으려는 내면의 움직임이 있습니다.',
    personalityFlow: '적응력이 좋고 다양한 상황에서 활력을 발휘하는 성향입니다. 변화를 즐기는 흐름이 있습니다.',
    emotionPattern: '감정이 상황에 따라 유연하게 변화하는 패턴입니다. 내면의 일관된 가치를 중심으로 잡는 것이 도움이 됩니다.',
    strengths: ['유연성', '적응력', '활력', '변화 수용'],
    complementColors: ['네이비', '그린'],
    recoveryDirection: '변화 속에서도 자신의 중심 가치를 기억하며 활력을 유지해보세요.',
    coachingMessage: '유연함은 당신의 강점입니다.\n그 유연함의 중심에 자신을 두세요.',
  },
  {
    id: 'orange_pentagon', color: 'orange', shape: 'pentagon',
    colorKor: '오렌지', shapeKor: '오각형', colorHex: '#FB8C00', shapeSymbol: '⬠',
    energyTitle: '다방면 활력 에너지',
    psychologyFlow: '여러 방향으로 활기차게 에너지가 뻗어나가는 흐름입니다. 다양한 관심사와 활동에서 즐거움을 찾으려는 마음이 활성화되어 있습니다.',
    personalityFlow: '다재다능하고 활발한 성향입니다. 다양한 분야에서 에너지를 발휘하는 흐름이 있습니다.',
    emotionPattern: '에너지가 여러 방향으로 분산되는 패턴입니다. 에너지를 집중할 방향을 정하는 것이 회복에 도움이 됩니다.',
    strengths: ['다재다능', '활력', '호기심', '사교성'],
    complementColors: ['네이비', '블루'],
    recoveryDirection: '다양한 활동 중 지금 가장 즐거운 하나에 집중하는 시간을 가져보세요.',
    coachingMessage: '당신의 활력은 많은 곳에서 빛납니다.\n지금은 가장 빛나는 곳에 집중해보세요.',
  },
  {
    id: 'orange_hexagon', color: 'orange', shape: 'hexagon',
    colorKor: '오렌지', shapeKor: '육각형', colorHex: '#FB8C00', shapeSymbol: '⬡',
    energyTitle: '활력의 네트워크',
    psychologyFlow: '활기찬 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 사람들과의 교류 속에서 에너지가 더욱 활성화되는 시기입니다.',
    personalityFlow: '사람들과의 연결을 통해 활력을 얻는 성향입니다. 협력과 소통에서 에너지가 충전되는 흐름이 있습니다.',
    emotionPattern: '관계 속에서 감정이 활발하게 교류되는 패턴입니다. 에너지를 주고받는 균형을 유지하는 것이 중요합니다.',
    strengths: ['연결력', '활력', '소통', '협력'],
    complementColors: ['블루', '화이트'],
    recoveryDirection: '관계 속에서 에너지를 주고받는 균형을 확인해보세요.',
    coachingMessage: '당신의 활력이 관계를 풍요롭게 합니다.\n그 관계 속에서 당신도 충전되고 있나요?',
  },

  // ─────────────────────────────────────────
  // 옐로우 (YELLOW) - 7장
  // ─────────────────────────────────────────
  {
    id: 'yellow_circle', color: 'yellow', shape: 'circle',
    colorKor: '옐로우', shapeKor: '동그라미', colorHex: '#FDD835', shapeSymbol: '○',
    energyTitle: '밝은 지성과 조화',
    psychologyFlow: '밝고 지적인 에너지가 주변과 조화를 이루는 흐름입니다. 호기심과 탐구심이 활성화되어 있으며 주변과 연결되고 싶은 마음이 흐르고 있습니다.',
    personalityFlow: '지적 호기심이 강하고 밝은 성향입니다. 배우고 탐구하는 것에서 기쁨을 얻는 흐름이 있습니다.',
    emotionPattern: '감정을 이성적으로 분석하려는 패턴이 있습니다. 때로는 감정을 그대로 느끼는 시간도 필요합니다.',
    strengths: ['지적 호기심', '밝음', '분석력', '소통'],
    complementColors: ['퍼플', '네이비'],
    recoveryDirection: '머리로 분석하는 것을 잠시 내려놓고, 감정을 그대로 느끼는 시간을 가져보세요.',
    coachingMessage: '당신의 밝은 지성이 세상을 더 잘 이해하게 합니다.\n가끔은 마음이 이끄는 대로 따라가 보세요.',
  },
  {
    id: 'yellow_triangle', color: 'yellow', shape: 'triangle',
    colorKor: '옐로우', shapeKor: '삼각형', colorHex: '#FDD835', shapeSymbol: '△',
    energyTitle: '지적 성장과 탐구',
    psychologyFlow: '지식과 지혜를 향해 위로 성장하려는 에너지가 흐르고 있습니다. 배움과 탐구를 통해 자신을 발전시키려는 의지가 강하게 활성화되어 있습니다.',
    personalityFlow: '학습 지향적이고 성장을 추구하는 성향입니다. 새로운 지식을 습득하는 것에서 큰 만족감을 얻는 흐름이 있습니다.',
    emotionPattern: '지적 자극이 부족할 때 감정적으로 불안정해질 수 있는 패턴입니다. 꾸준한 배움의 흐름이 감정 안정에도 도움이 됩니다.',
    strengths: ['학습 능력', '성장 의지', '탐구심', '분석력'],
    complementColors: ['퍼플', '블루'],
    recoveryDirection: '지적 탐구와 함께 감정적인 성장도 함께 이루어지도록 균형을 잡아보세요.',
    coachingMessage: '배움을 향한 당신의 열정이 빛납니다.\n지식과 함께 마음도 함께 성장하고 있습니다.',
  },
  {
    id: 'yellow_inverted_triangle', color: 'yellow', shape: 'inverted_triangle',
    colorKor: '옐로우', shapeKor: '역삼각형', colorHex: '#FDD835', shapeSymbol: '▽',
    energyTitle: '지혜의 내면화',
    psychologyFlow: '쌓아온 지식과 경험이 내면으로 깊이 흘러들어가 지혜로 변환되는 흐름입니다. 외부 자극보다 내면의 통찰을 통해 성장하는 시기입니다.',
    personalityFlow: '깊이 생각하고 내면화하는 성향입니다. 경험에서 의미를 찾고 지혜를 쌓아가는 흐름이 있습니다.',
    emotionPattern: '생각이 깊어지면서 감정도 함께 깊어지는 패턴입니다. 내면의 통찰을 신뢰하는 것이 회복에 도움이 됩니다.',
    strengths: ['깊은 사고', '내면화', '지혜', '통찰력'],
    complementColors: ['오렌지', '그린'],
    recoveryDirection: '내면의 지혜를 신뢰하고, 그 통찰을 삶에 적용해보세요.',
    coachingMessage: '당신 안에 이미 많은 지혜가 있습니다.\n그 지혜를 신뢰하고 따라가 보세요.',
  },
  {
    id: 'yellow_square', color: 'yellow', shape: 'square',
    colorKor: '옐로우', shapeKor: '네모', colorHex: '#FDD835', shapeSymbol: '□',
    energyTitle: '체계적 지성',
    psychologyFlow: '지적 에너지를 체계적이고 구조적으로 사용하려는 흐름입니다. 정리되고 명확한 방식으로 생각하고 행동하려는 마음이 흐르고 있습니다.',
    personalityFlow: '체계적이고 논리적인 성향입니다. 명확한 구조 안에서 지적 능력을 발휘하는 흐름이 있습니다.',
    emotionPattern: '모든 것을 논리적으로 이해하려는 패턴이 있습니다. 논리로 설명되지 않는 감정도 있다는 것을 받아들이는 것이 도움이 됩니다.',
    strengths: ['논리적 사고', '체계성', '명확성', '분석력'],
    complementColors: ['오렌지', '퍼플'],
    recoveryDirection: '논리와 감성의 균형을 찾아보세요. 때로는 감정이 더 정확한 답을 줍니다.',
    coachingMessage: '당신의 체계적인 사고가 많은 것을 이루게 합니다.\n감성도 함께 허용할 때 더 풍요로워집니다.',
  },
  {
    id: 'yellow_diamond', color: 'yellow', shape: 'diamond',
    colorKor: '옐로우', shapeKor: '마름모', colorHex: '#FDD835', shapeSymbol: '◇',
    energyTitle: '유연한 지성',
    psychologyFlow: '다양한 관점에서 유연하게 생각하는 에너지가 흐르고 있습니다. 고정된 틀을 벗어나 새로운 시각으로 바라보려는 내면의 움직임이 있습니다.',
    personalityFlow: '유연하고 다각적인 사고를 하는 성향입니다. 다양한 관점을 수용하고 통합하는 흐름이 있습니다.',
    emotionPattern: '다양한 가능성을 생각하다 결정을 미루는 패턴이 있습니다. 완벽한 답보다 지금의 최선을 선택하는 연습이 도움이 됩니다.',
    strengths: ['유연한 사고', '다각적 시각', '창의성', '개방성'],
    complementColors: ['네이비', '퍼플'],
    recoveryDirection: '다양한 가능성을 탐색한 후, 지금 가장 맞는 방향을 선택해보세요.',
    coachingMessage: '다양한 시각을 가진 당신이 더 넓은 세상을 봅니다.\n지금은 하나를 선택하고 나아갈 시간입니다.',
  },
  {
    id: 'yellow_pentagon', color: 'yellow', shape: 'pentagon',
    colorKor: '옐로우', shapeKor: '오각형', colorHex: '#FDD835', shapeSymbol: '⬠',
    energyTitle: '다방면 지적 탐구',
    psychologyFlow: '다양한 분야에 대한 지적 호기심이 동시에 활성화되는 흐름입니다. 여러 방향으로 탐구하고 배우려는 에너지가 넘치는 시기입니다.',
    personalityFlow: '다방면에 관심이 많고 지적 탐구를 즐기는 성향입니다. 다양한 분야를 연결하는 통합적 사고를 하는 흐름이 있습니다.',
    emotionPattern: '관심사가 너무 많아 집중하기 어려운 패턴이 있습니다. 지금 가장 중요한 탐구 주제를 정하는 것이 도움이 됩니다.',
    strengths: ['다방면 지식', '통합적 사고', '호기심', '탐구심'],
    complementColors: ['네이비', '블루'],
    recoveryDirection: '다양한 관심사 중 지금 가장 깊이 탐구하고 싶은 하나를 선택해보세요.',
    coachingMessage: '당신의 지적 호기심은 세상을 더 풍요롭게 합니다.\n지금은 하나를 깊이 파고드는 시간입니다.',
  },
  {
    id: 'yellow_hexagon', color: 'yellow', shape: 'hexagon',
    colorKor: '옐로우', shapeKor: '육각형', colorHex: '#FDD835', shapeSymbol: '⬡',
    energyTitle: '지성의 연결망',
    psychologyFlow: '지적 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 지식을 나누고 소통하면서 더 큰 이해에 도달하려는 움직임이 있습니다.',
    personalityFlow: '지식을 나누고 소통하는 것을 즐기는 성향입니다. 가르치고 배우는 상호 교류에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '지식을 나누는 것에서 감정적 만족을 얻는 패턴입니다. 깊이 있는 대화와 교류가 감정 회복에도 도움이 됩니다.',
    strengths: ['지식 공유', '소통', '연결력', '교육적 성향'],
    complementColors: ['퍼플', '블루'],
    recoveryDirection: '지식을 나누는 것에서 오는 기쁨을 충분히 누려보세요.',
    coachingMessage: '당신이 나누는 지식이 주변을 밝힙니다.\n그 나눔 속에서 당신도 더 성장합니다.',
  },

  // ─────────────────────────────────────────
  // 그린 (GREEN) - 7장
  // ─────────────────────────────────────────
  {
    id: 'green_circle', color: 'green', shape: 'circle',
    colorKor: '그린', shapeKor: '동그라미', colorHex: '#43A047', shapeSymbol: '○',
    energyTitle: '안정과 조화',
    psychologyFlow: '자연스러운 안정감과 조화로운 에너지가 흐르고 있습니다. 주변과 균형을 이루며 평화로운 상태를 유지하려는 마음이 흐르고 있습니다.',
    personalityFlow: '안정적이고 균형 잡힌 성향입니다. 조화로운 환경에서 에너지가 자연스럽게 회복되는 흐름이 있습니다.',
    emotionPattern: '감정이 안정적으로 흐르는 패턴입니다. 갈등 상황에서 조화를 찾으려는 노력이 강하게 나타납니다.',
    strengths: ['안정감', '조화', '균형', '치유 에너지'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '자연과 함께하는 시간이나 조용한 환경에서 에너지를 회복해보세요.',
    coachingMessage: '당신의 안정된 에너지가 주변을 편안하게 합니다.\n그 안정 속에서 자신도 충분히 쉬어가세요.',
  },
  {
    id: 'green_triangle', color: 'green', shape: 'triangle',
    colorKor: '그린', shapeKor: '삼각형', colorHex: '#43A047', shapeSymbol: '△',
    energyTitle: '성장 의지',
    psychologyFlow: '안정적인 기반 위에서 위로 성장하려는 에너지가 흐르고 있습니다. 천천히 하지만 꾸준하게 앞으로 나아가려는 의지가 활성화되어 있습니다.',
    personalityFlow: '꾸준하고 성실한 성향입니다. 급하게 달리기보다 안정적으로 성장하는 흐름을 선호합니다.',
    emotionPattern: '성장 과정에서 조급함을 느낄 수 있는 패턴입니다. 자신의 속도를 신뢰하는 것이 중요합니다.',
    strengths: ['꾸준함', '성실함', '성장 의지', '안정적 추진력'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '자신의 성장 속도를 신뢰하고, 작은 진전에도 충분히 기뻐해보세요.',
    coachingMessage: '천천히 하지만 꾸준히 성장하는 당신입니다.\n그 속도가 바로 당신의 강점입니다.',
  },
  {
    id: 'green_inverted_triangle', color: 'green', shape: 'inverted_triangle',
    colorKor: '그린', shapeKor: '역삼각형', colorHex: '#43A047', shapeSymbol: '▽',
    energyTitle: '치유와 내면 회복',
    psychologyFlow: '치유 에너지가 내면 깊이 흘러들어가 회복을 이루는 흐름입니다. 지쳐있던 마음이 자연스럽게 회복되는 시기입니다.',
    personalityFlow: '치유적이고 돌봄의 성향이 강합니다. 자신과 타인을 돌보는 것에서 의미를 찾는 흐름이 있습니다.',
    emotionPattern: '타인을 돌보느라 자신의 회복을 미루는 패턴이 있습니다. 자신을 먼저 돌보는 것이 더 많은 것을 줄 수 있게 합니다.',
    strengths: ['치유력', '돌봄', '공감', '회복 에너지'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '타인을 돌보기 전에 자신을 먼저 충분히 돌보는 시간을 가져보세요.',
    coachingMessage: '당신의 치유 에너지가 많은 사람들을 회복시킵니다.\n그 에너지의 원천인 당신 자신도 돌봐주세요.',
  },
  {
    id: 'green_square', color: 'green', shape: 'square',
    colorKor: '그린', shapeKor: '네모', colorHex: '#43A047', shapeSymbol: '□',
    energyTitle: '안정적 성장 기반',
    psychologyFlow: '안정적인 기반을 구축하며 성장하려는 에너지가 흐르고 있습니다. 체계적이고 안정적인 방식으로 목표를 이루어가려는 마음이 흐르고 있습니다.',
    personalityFlow: '안정적이고 체계적인 성향입니다. 튼튼한 기반 위에서 성장하는 것을 중요하게 여기는 흐름이 있습니다.',
    emotionPattern: '변화보다 안정을 선호하는 패턴입니다. 필요한 변화를 받아들이는 유연성도 함께 키워가는 것이 도움이 됩니다.',
    strengths: ['안정성', '체계성', '꾸준함', '기반 구축'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '안정적인 기반을 유지하면서도 새로운 가능성에 조금씩 열려보세요.',
    coachingMessage: '튼튼한 기반이 있어 더 높이 성장할 수 있습니다.\n그 기반 위에서 새로운 가능성도 탐색해보세요.',
  },
  {
    id: 'green_diamond', color: 'green', shape: 'diamond',
    colorKor: '그린', shapeKor: '마름모', colorHex: '#43A047', shapeSymbol: '◇',
    energyTitle: '유연한 성장',
    psychologyFlow: '안정적이면서도 유연하게 성장하는 에너지가 흐르고 있습니다. 상황에 따라 적응하면서도 자신의 중심을 잃지 않으려는 흐름이 있습니다.',
    personalityFlow: '유연하고 적응력이 좋은 성향입니다. 변화 속에서도 안정감을 유지하는 흐름이 있습니다.',
    emotionPattern: '변화와 안정 사이에서 균형을 찾으려는 패턴입니다. 두 가지 모두 필요하다는 것을 인정하는 것이 도움이 됩니다.',
    strengths: ['유연성', '적응력', '안정감', '균형'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '변화와 안정 사이에서 자신에게 맞는 균형점을 찾아보세요.',
    coachingMessage: '유연하게 적응하면서도 자신을 잃지 않는 당신입니다.\n그 균형이 당신의 강점입니다.',
  },
  {
    id: 'green_pentagon', color: 'green', shape: 'pentagon',
    colorKor: '그린', shapeKor: '오각형', colorHex: '#43A047', shapeSymbol: '⬠',
    energyTitle: '다방면 성장 에너지',
    psychologyFlow: '여러 방향으로 성장하려는 에너지가 흐르고 있습니다. 다양한 분야에서 안정적으로 성장하려는 마음이 활성화되어 있습니다.',
    personalityFlow: '다방면으로 성장을 추구하는 성향입니다. 다양한 분야에서 균형 있게 발전하는 흐름이 있습니다.',
    emotionPattern: '여러 방향으로 에너지가 분산되면서 피로감을 느낄 수 있는 패턴입니다. 우선순위를 정하고 집중하는 것이 도움이 됩니다.',
    strengths: ['다방면 성장', '균형', '꾸준함', '다재다능'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '다양한 성장 방향 중 지금 가장 중요한 하나에 집중해보세요.',
    coachingMessage: '다방면으로 성장하는 당신은 풍요로운 사람입니다.\n지금은 가장 중요한 성장에 집중할 시간입니다.',
  },
  {
    id: 'green_hexagon', color: 'green', shape: 'hexagon',
    colorKor: '그린', shapeKor: '육각형', colorHex: '#43A047', shapeSymbol: '⬡',
    energyTitle: '치유의 연결망',
    psychologyFlow: '치유 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 관계 속에서 치유와 회복이 이루어지는 시기입니다.',
    personalityFlow: '관계 속에서 치유와 성장을 이루는 성향입니다. 공동체와의 연결에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '관계 속에서 감정이 치유되는 패턴입니다. 건강한 관계가 감정 회복에 큰 도움이 됩니다.',
    strengths: ['치유력', '연결력', '공동체 의식', '돌봄'],
    complementColors: ['레드', '오렌지'],
    recoveryDirection: '신뢰할 수 있는 관계 속에서 치유의 시간을 가져보세요.',
    coachingMessage: '관계 속에서 치유되는 당신입니다.\n그 연결이 당신을 더 강하게 만들어줍니다.',
  },

  // ─────────────────────────────────────────
  // 블루 (BLUE) - 7장
  // ─────────────────────────────────────────
  {
    id: 'blue_circle', color: 'blue', shape: 'circle',
    colorKor: '블루', shapeKor: '동그라미', colorHex: '#1E88E5', shapeSymbol: '○',
    energyTitle: '평화로운 소통',
    psychologyFlow: '맑고 평화로운 에너지가 주변과 조화롭게 흐르고 있습니다. 진실된 소통과 연결을 통해 마음의 평화를 찾으려는 흐름이 이어지고 있습니다.',
    personalityFlow: '진실하고 소통을 중요하게 여기는 성향입니다. 깊은 대화와 진정한 연결에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '감정을 솔직하게 표현하고 싶지만 상대방을 배려하는 패턴이 있습니다. 자신의 감정도 충분히 표현하는 연습이 도움이 됩니다.',
    strengths: ['소통력', '진실성', '평화 추구', '공감 능력'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '진실된 소통을 통해 마음의 평화를 찾아보세요.',
    coachingMessage: '당신의 진실한 소통이 관계를 깊게 합니다.\n자신의 마음도 솔직하게 표현해보세요.',
  },
  {
    id: 'blue_triangle', color: 'blue', shape: 'triangle',
    colorKor: '블루', shapeKor: '삼각형', colorHex: '#1E88E5', shapeSymbol: '△',
    energyTitle: '진실을 향한 성장',
    psychologyFlow: '진실과 지혜를 향해 성장하려는 에너지가 흐르고 있습니다. 더 깊은 이해와 진실을 추구하는 내면의 움직임이 활성화되어 있습니다.',
    personalityFlow: '진실을 추구하고 깊이 있는 성장을 원하는 성향입니다. 표면적인 것보다 본질을 탐구하는 흐름이 있습니다.',
    emotionPattern: '이상과 현실 사이에서 갈등을 느낄 수 있는 패턴입니다. 현실 속에서 이상을 향해 나아가는 균형이 중요합니다.',
    strengths: ['진실 추구', '깊은 사고', '이상주의', '성장 의지'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '이상을 향해 나아가면서도 현실의 작은 아름다움도 발견해보세요.',
    coachingMessage: '진실을 향한 당신의 여정이 아름답습니다.\n현실 속에서도 그 진실을 발견할 수 있습니다.',
  },
  {
    id: 'blue_inverted_triangle', color: 'blue', shape: 'inverted_triangle',
    colorKor: '블루', shapeKor: '역삼각형', colorHex: '#1E88E5', shapeSymbol: '▽',
    energyTitle: '감정의 정화와 평화',
    psychologyFlow: '감정이 맑게 정화되며 내면의 평화를 찾아가는 흐름입니다. 복잡했던 감정들이 자연스럽게 정리되는 시기입니다.',
    personalityFlow: '감정을 깊이 느끼고 정화하는 성향입니다. 내면의 평화를 중요하게 여기는 흐름이 있습니다.',
    emotionPattern: '감정을 내면에서 처리하는 패턴이 있습니다. 신뢰하는 사람과의 대화가 감정 정화에 도움이 됩니다.',
    strengths: ['감정 정화', '내면 평화', '깊은 감수성', '진정성'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '감정을 안전하게 정화할 수 있는 공간과 시간을 만들어보세요.',
    coachingMessage: '감정을 정화하는 당신의 흐름이 내면을 맑게 합니다.\n그 평화로운 공간을 충분히 누려보세요.',
  },
  {
    id: 'blue_square', color: 'blue', shape: 'square',
    colorKor: '블루', shapeKor: '네모', colorHex: '#1E88E5', shapeSymbol: '□',
    energyTitle: '신뢰와 안정',
    psychologyFlow: '신뢰할 수 있는 안정적인 환경을 구축하려는 에너지가 흐르고 있습니다. 체계적이고 신뢰 있는 관계와 환경을 원하는 마음이 흐르고 있습니다.',
    personalityFlow: '신뢰와 안정을 중요하게 여기는 성향입니다. 약속을 지키고 일관성 있는 행동을 하는 흐름이 있습니다.',
    emotionPattern: '신뢰가 깨질 때 감정적으로 크게 흔들리는 패턴이 있습니다. 자신을 신뢰하는 것부터 시작하는 것이 도움이 됩니다.',
    strengths: ['신뢰성', '안정성', '일관성', '책임감'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '자신을 신뢰하는 것에서 시작하여 건강한 신뢰 관계를 만들어가보세요.',
    coachingMessage: '신뢰는 자신에서 시작됩니다.\n당신 자신을 먼저 신뢰해보세요.',
  },
  {
    id: 'blue_diamond', color: 'blue', shape: 'diamond',
    colorKor: '블루', shapeKor: '마름모', colorHex: '#1E88E5', shapeSymbol: '◇',
    energyTitle: '유연한 소통',
    psychologyFlow: '다양한 상황에서 유연하게 소통하는 에너지가 흐르고 있습니다. 상황에 맞게 소통 방식을 조절하면서도 진실성을 유지하려는 흐름이 있습니다.',
    personalityFlow: '유연하고 상황 적응적인 소통을 하는 성향입니다. 다양한 사람들과 자연스럽게 연결되는 흐름이 있습니다.',
    emotionPattern: '소통 방식을 상황에 맞게 조절하는 패턴입니다. 자신의 진실한 목소리도 잃지 않는 것이 중요합니다.',
    strengths: ['유연한 소통', '적응력', '공감 능력', '연결력'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '유연하게 소통하면서도 자신의 진실한 목소리를 지켜보세요.',
    coachingMessage: '유연하게 소통하는 당신은 많은 관계를 풍요롭게 합니다.\n자신의 목소리도 그 안에 포함시켜 주세요.',
  },
  {
    id: 'blue_pentagon', color: 'blue', shape: 'pentagon',
    colorKor: '블루', shapeKor: '오각형', colorHex: '#1E88E5', shapeSymbol: '⬠',
    energyTitle: '다방면 소통 에너지',
    psychologyFlow: '다양한 방향으로 소통하고 연결하려는 에너지가 흐르고 있습니다. 여러 관계와 분야에서 진실된 소통을 원하는 마음이 활성화되어 있습니다.',
    personalityFlow: '다방면에서 소통하고 연결하는 성향입니다. 다양한 사람들과 깊은 관계를 맺는 흐름이 있습니다.',
    emotionPattern: '많은 관계를 유지하면서 에너지가 분산될 수 있는 패턴입니다. 깊이 있는 소수의 관계에 집중하는 것이 도움이 됩니다.',
    strengths: ['소통력', '연결력', '다양성', '공감 능력'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '다양한 관계 중 깊이 있는 소통이 가능한 관계에 더 집중해보세요.',
    coachingMessage: '많은 관계 속에서 소통하는 당신입니다.\n깊이 있는 연결이 더 큰 에너지를 줍니다.',
  },
  {
    id: 'blue_hexagon', color: 'blue', shape: 'hexagon',
    colorKor: '블루', shapeKor: '육각형', colorHex: '#1E88E5', shapeSymbol: '⬡',
    energyTitle: '소통의 연결망',
    psychologyFlow: '소통 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 관계의 네트워크를 통해 더 큰 이해와 평화를 찾으려는 움직임이 있습니다.',
    personalityFlow: '관계 네트워크를 통해 소통하고 성장하는 성향입니다. 공동체 안에서 진실된 연결을 만들어가는 흐름이 있습니다.',
    emotionPattern: '관계 네트워크 속에서 감정이 교류되는 패턴입니다. 건강한 경계를 유지하면서 연결하는 것이 중요합니다.',
    strengths: ['네트워킹', '소통력', '공동체 의식', '연결력'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '관계 네트워크 속에서 자신의 에너지를 지키는 경계를 확인해보세요.',
    coachingMessage: '소통의 연결망을 만드는 당신입니다.\n그 연결 속에서 자신도 충분히 돌봐주세요.',
  },

  // ─────────────────────────────────────────
  // 네이비 (NAVY) - 7장
  // ─────────────────────────────────────────
  {
    id: 'navy_circle', color: 'navy', shape: 'circle',
    colorKor: '네이비', shapeKor: '동그라미', colorHex: '#283593', shapeSymbol: '○',
    energyTitle: '깊은 지혜와 포용',
    psychologyFlow: '깊은 내면의 지혜가 조용히 흐르고 있습니다. 깊이 생각하고 이해하려는 에너지가 주변을 포용하는 방향으로 흐르고 있습니다.',
    personalityFlow: '깊이 있고 사려 깊은 성향입니다. 표면적인 것보다 본질을 이해하려는 흐름이 있습니다.',
    emotionPattern: '감정을 깊이 내면화하는 패턴이 있습니다. 신뢰하는 사람과의 깊은 대화가 감정 표현에 도움이 됩니다.',
    strengths: ['깊은 지혜', '사려 깊음', '통찰력', '포용력'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '내면의 깊은 지혜를 신뢰하고, 그것을 조금씩 표현해보세요.',
    coachingMessage: '당신 안의 깊은 지혜가 조용히 빛나고 있습니다.\n그 지혜를 세상과 나눌 시간입니다.',
  },
  {
    id: 'navy_triangle', color: 'navy', shape: 'triangle',
    colorKor: '네이비', shapeKor: '삼각형', colorHex: '#283593', shapeSymbol: '△',
    energyTitle: '깊은 성장 의지',
    psychologyFlow: '깊은 내면에서 성장하려는 강한 의지가 흐르고 있습니다. 표면적인 성장보다 내면의 깊이 있는 성장을 추구하는 에너지가 활성화되어 있습니다.',
    personalityFlow: '깊이 있는 성장을 추구하는 성향입니다. 빠른 성장보다 의미 있는 성장을 중요하게 여기는 흐름이 있습니다.',
    emotionPattern: '높은 기준을 가지고 있어 스스로에게 엄격한 패턴이 있습니다. 자신의 성장 과정을 인정하고 격려하는 것이 도움이 됩니다.',
    strengths: ['깊은 성장 의지', '높은 기준', '내면 성숙', '통찰력'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '자신의 성장 과정을 인정하고, 이미 이룬 것들에 대해 스스로를 격려해보세요.',
    coachingMessage: '깊이 있는 성장을 추구하는 당신입니다.\n그 과정에서 자신을 충분히 격려해주세요.',
  },
  {
    id: 'navy_inverted_triangle', color: 'navy', shape: 'inverted_triangle',
    colorKor: '네이비', shapeKor: '역삼각형', colorHex: '#283593', shapeSymbol: '▽',
    energyTitle: '내면 성찰과 깊은 회복',
    psychologyFlow: '깊은 내면 성찰을 통해 회복이 이루어지는 흐름입니다. 조용히 자신을 돌아보며 내면의 깊은 곳에서 치유가 일어나는 시기입니다.',
    personalityFlow: '깊은 성찰과 내면 탐구를 즐기는 성향입니다. 혼자만의 시간에서 에너지를 회복하는 흐름이 있습니다.',
    emotionPattern: '감정을 깊이 내면에서 처리하는 패턴이 있습니다. 충분한 혼자만의 시간이 감정 회복에 도움이 됩니다.',
    strengths: ['깊은 성찰', '내면 탐구', '자기 이해', '회복력'],
    complementColors: ['오렌지', '레드'],
    recoveryDirection: '혼자만의 조용한 시간을 통해 내면의 깊은 회복을 경험해보세요.',
    coachingMessage: '깊이 성찰하는 당신의 내면에서 회복이 일어나고 있습니다.\n그 조용한 시간을 충분히 허용해주세요.',
  },
  {
    id: 'navy_square', color: 'navy', shape: 'square',
    colorKor: '네이비', shapeKor: '네모', colorHex: '#283593', shapeSymbol: '□',
    energyTitle: '깊은 신뢰와 안정',
    psychologyFlow: '깊은 신뢰와 안정을 구축하려는 에너지가 흐르고 있습니다. 오랜 시간에 걸쳐 쌓아온 신뢰와 안정을 소중히 여기는 마음이 흐르고 있습니다.',
    personalityFlow: '깊은 신뢰와 안정을 중요하게 여기는 성향입니다. 오랜 관계와 검증된 방식을 선호하는 흐름이 있습니다.',
    emotionPattern: '변화에 대한 저항감이 있을 수 있는 패턴입니다. 안정 속에서도 새로운 가능성을 탐색하는 것이 성장에 도움이 됩니다.',
    strengths: ['깊은 신뢰', '안정성', '일관성', '책임감'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '안정적인 기반을 유지하면서도 새로운 가능성에 조금씩 열려보세요.',
    coachingMessage: '깊은 신뢰와 안정이 당신의 강점입니다.\n그 안정 위에서 새로운 가능성도 탐색해보세요.',
  },
  {
    id: 'navy_diamond', color: 'navy', shape: 'diamond',
    colorKor: '네이비', shapeKor: '마름모', colorHex: '#283593', shapeSymbol: '◇',
    energyTitle: '깊은 유연성',
    psychologyFlow: '깊은 내면에서 유연하게 변화를 수용하는 에너지가 흐르고 있습니다. 깊이 있는 사고를 바탕으로 유연하게 적응하려는 흐름이 있습니다.',
    personalityFlow: '깊이 생각하면서도 유연하게 적응하는 성향입니다. 변화를 깊이 이해한 후 수용하는 흐름이 있습니다.',
    emotionPattern: '변화를 깊이 분석하다 결정이 늦어지는 패턴이 있습니다. 충분한 분석 후 과감하게 결정하는 연습이 도움이 됩니다.',
    strengths: ['깊은 사고', '유연성', '분석력', '적응력'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '깊이 분석한 후에는 과감하게 결정하고 나아가는 연습을 해보세요.',
    coachingMessage: '깊이 생각하고 유연하게 적응하는 당신입니다.\n충분히 생각했다면 이제 나아갈 시간입니다.',
  },
  {
    id: 'navy_pentagon', color: 'navy', shape: 'pentagon',
    colorKor: '네이비', shapeKor: '오각형', colorHex: '#283593', shapeSymbol: '⬠',
    energyTitle: '다방면 깊은 탐구',
    psychologyFlow: '다양한 방향으로 깊이 탐구하려는 에너지가 흐르고 있습니다. 여러 분야를 깊이 있게 이해하려는 내면의 움직임이 활성화되어 있습니다.',
    personalityFlow: '다방면에 깊은 관심을 가지는 성향입니다. 다양한 분야를 깊이 탐구하는 흐름이 있습니다.',
    emotionPattern: '깊이 탐구하다 에너지가 분산될 수 있는 패턴입니다. 지금 가장 깊이 탐구하고 싶은 하나에 집중하는 것이 도움이 됩니다.',
    strengths: ['깊은 탐구', '다방면 지식', '통찰력', '분석력'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '다양한 탐구 주제 중 지금 가장 깊이 파고들고 싶은 하나를 선택해보세요.',
    coachingMessage: '깊이 탐구하는 당신의 지식이 세상을 풍요롭게 합니다.\n지금은 하나에 집중하는 깊이의 시간입니다.',
  },
  {
    id: 'navy_hexagon', color: 'navy', shape: 'hexagon',
    colorKor: '네이비', shapeKor: '육각형', colorHex: '#283593', shapeSymbol: '⬡',
    energyTitle: '깊은 연결의 네트워크',
    psychologyFlow: '깊은 이해를 바탕으로 한 연결이 확장되는 흐름입니다. 표면적인 연결보다 깊이 있는 관계를 통해 성장하려는 움직임이 있습니다.',
    personalityFlow: '깊이 있는 관계를 중요하게 여기는 성향입니다. 소수의 깊은 관계에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '깊은 관계를 원하지만 쉽게 마음을 열지 못하는 패턴이 있습니다. 신뢰할 수 있는 관계에서 조금씩 마음을 여는 것이 도움이 됩니다.',
    strengths: ['깊은 관계', '신뢰', '통찰력', '연결력'],
    complementColors: ['오렌지', '옐로우'],
    recoveryDirection: '신뢰할 수 있는 사람에게 조금씩 마음을 열어보세요.',
    coachingMessage: '깊은 연결을 원하는 당신입니다.\n신뢰하는 한 사람에게 먼저 마음을 열어보세요.',
  },

  // ─────────────────────────────────────────
  // 퍼플 (PURPLE) - 7장
  // ─────────────────────────────────────────
  {
    id: 'purple_circle', color: 'purple', shape: 'circle',
    colorKor: '퍼플', shapeKor: '동그라미', colorHex: '#8E24AA', shapeSymbol: '○',
    energyTitle: '영적 포용과 직관',
    psychologyFlow: '깊은 직관과 영적 감수성이 주변을 포용하는 방향으로 흐르고 있습니다. 내면의 깊은 지혜와 직관을 통해 세상을 이해하려는 흐름이 있습니다.',
    personalityFlow: '직관적이고 영적 감수성이 풍부한 성향입니다. 눈에 보이지 않는 것들을 감지하는 능력이 있는 흐름이 있습니다.',
    emotionPattern: '감정과 직관이 함께 작동하는 패턴입니다. 직관을 신뢰하면서도 현실적인 판단도 함께 하는 것이 도움이 됩니다.',
    strengths: ['직관력', '영적 감수성', '포용력', '깊은 이해'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '내면의 직관을 신뢰하고, 그것이 이끄는 방향으로 조금씩 나아가보세요.',
    coachingMessage: '당신의 깊은 직관이 길을 안내합니다.\n그 내면의 목소리를 신뢰해보세요.',
  },
  {
    id: 'purple_triangle', color: 'purple', shape: 'triangle',
    colorKor: '퍼플', shapeKor: '삼각형', colorHex: '#8E24AA', shapeSymbol: '△',
    energyTitle: '영적 성장과 깨달음',
    psychologyFlow: '영적 성장과 깊은 깨달음을 향해 나아가는 에너지가 흐르고 있습니다. 더 높은 차원의 이해와 의식 성장을 추구하는 내면의 움직임이 활성화되어 있습니다.',
    personalityFlow: '영적 성장과 깨달음을 추구하는 성향입니다. 삶의 깊은 의미를 탐구하는 흐름이 있습니다.',
    emotionPattern: '높은 이상을 추구하다 현실과의 괴리감을 느낄 수 있는 패턴입니다. 영적 성장과 현실 삶의 균형을 찾는 것이 중요합니다.',
    strengths: ['영적 성장', '깊은 통찰', '이상 추구', '의미 탐구'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '영적 성장을 추구하면서도 현실 삶의 아름다움도 함께 발견해보세요.',
    coachingMessage: '영적 성장을 향한 당신의 여정이 아름답습니다.\n현실 속에서도 그 성장이 빛날 수 있습니다.',
  },
  {
    id: 'purple_inverted_triangle', color: 'purple', shape: 'inverted_triangle',
    colorKor: '퍼플', shapeKor: '역삼각형', colorHex: '#8E24AA', shapeSymbol: '▽',
    energyTitle: '내면 성찰과 감정 소진 회복',
    psychologyFlow: '깊은 내면 성찰을 통해 감정이 재정렬되는 흐름입니다. 억눌려 있던 감정들이 조용히 표면으로 올라와 정화되는 시기입니다.',
    personalityFlow: '깊은 내면 성찰을 통해 감정을 정화하는 성향입니다. 혼자만의 시간에서 깊은 회복을 경험하는 흐름이 있습니다.',
    emotionPattern: '감정을 깊이 내면화하다 소진될 수 있는 패턴이 있습니다. 감정을 안전하게 표현하고 정화하는 시간이 필요합니다.',
    strengths: ['깊은 성찰', '감정 정화', '내면 탐구', '직관력'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '억눌린 감정을 안전하게 꺼내고 정화하는 시간을 가져보세요.',
    coachingMessage: '깊은 내면에서 감정이 정화되고 있습니다.\n그 과정을 충분히 허용하고 지지해주세요.',
  },
  {
    id: 'purple_square', color: 'purple', shape: 'square',
    colorKor: '퍼플', shapeKor: '네모', colorHex: '#8E24AA', shapeSymbol: '□',
    energyTitle: '영적 구조와 안정',
    psychologyFlow: '영적 가치를 체계적으로 삶에 적용하려는 에너지가 흐르고 있습니다. 깊은 내면의 가치를 안정적인 삶의 구조로 만들어가려는 흐름이 있습니다.',
    personalityFlow: '영적 가치와 실용적 삶을 통합하려는 성향입니다. 내면의 가치를 현실에서 구현하는 것을 중요하게 여기는 흐름이 있습니다.',
    emotionPattern: '이상적인 가치와 현실 사이에서 갈등을 느낄 수 있는 패턴입니다. 완벽한 실현보다 점진적인 통합이 더 건강한 방향입니다.',
    strengths: ['영적 가치', '체계성', '통합력', '안정 추구'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '영적 가치를 현실에서 조금씩 실현해가는 과정을 즐겨보세요.',
    coachingMessage: '내면의 가치를 현실에서 구현하는 당신입니다.\n완벽하지 않아도 그 방향으로 나아가는 것이 아름답습니다.',
  },
  {
    id: 'purple_diamond', color: 'purple', shape: 'diamond',
    colorKor: '퍼플', shapeKor: '마름모', colorHex: '#8E24AA', shapeSymbol: '◇',
    energyTitle: '직관적 유연성',
    psychologyFlow: '깊은 직관을 바탕으로 유연하게 변화를 수용하는 에너지가 흐르고 있습니다. 직관이 이끄는 방향으로 유연하게 나아가려는 흐름이 있습니다.',
    personalityFlow: '직관적이고 유연한 성향입니다. 직관을 신뢰하며 변화를 수용하는 흐름이 있습니다.',
    emotionPattern: '직관과 이성 사이에서 갈등을 느낄 수 있는 패턴입니다. 직관을 신뢰하면서도 현실적 판단을 함께 하는 것이 도움이 됩니다.',
    strengths: ['직관력', '유연성', '변화 수용', '창의성'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '직관이 이끄는 방향을 신뢰하면서 현실적인 판단도 함께 해보세요.',
    coachingMessage: '당신의 직관은 신뢰할 수 있는 안내자입니다.\n그 직관과 현실의 균형을 찾아보세요.',
  },
  {
    id: 'purple_pentagon', color: 'purple', shape: 'pentagon',
    colorKor: '퍼플', shapeKor: '오각형', colorHex: '#8E24AA', shapeSymbol: '⬠',
    energyTitle: '다방면 영적 탐구',
    psychologyFlow: '다양한 방향으로 영적 탐구를 하려는 에너지가 흐르고 있습니다. 여러 영적 주제와 내면의 깊은 질문들을 탐구하는 시기입니다.',
    personalityFlow: '다방면의 영적 탐구를 즐기는 성향입니다. 다양한 영적 주제에 깊은 관심을 가지는 흐름이 있습니다.',
    emotionPattern: '다양한 영적 탐구 속에서 방향을 잃을 수 있는 패턴이 있습니다. 자신의 핵심 가치를 중심으로 탐구 방향을 잡는 것이 도움이 됩니다.',
    strengths: ['영적 탐구', '다방면 관심', '직관력', '깊은 이해'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '다양한 영적 탐구 중 자신의 핵심 가치와 가장 연결되는 방향을 찾아보세요.',
    coachingMessage: '다방면으로 탐구하는 당신의 영적 여정이 깊어지고 있습니다.\n그 여정의 중심에 자신의 핵심 가치를 두세요.',
  },
  {
    id: 'purple_hexagon', color: 'purple', shape: 'hexagon',
    colorKor: '퍼플', shapeKor: '육각형', colorHex: '#8E24AA', shapeSymbol: '⬡',
    energyTitle: '영적 연결의 네트워크',
    psychologyFlow: '영적 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 깊은 영적 연결과 공동체를 통해 성장하려는 움직임이 있습니다.',
    personalityFlow: '영적 공동체와의 연결을 중요하게 여기는 성향입니다. 같은 가치를 공유하는 사람들과의 연결에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '영적 공동체 안에서 감정이 교류되는 패턴입니다. 건강한 영적 연결이 감정 회복에도 도움이 됩니다.',
    strengths: ['영적 연결', '공동체 의식', '직관력', '포용력'],
    complementColors: ['옐로우', '오렌지'],
    recoveryDirection: '같은 가치를 공유하는 사람들과의 연결을 통해 에너지를 회복해보세요.',
    coachingMessage: '영적 연결을 통해 성장하는 당신입니다.\n그 연결 속에서 더 깊은 회복이 일어납니다.',
  },

  // ─────────────────────────────────────────
  // 화이트 (WHITE) - 7장
  // ─────────────────────────────────────────
  {
    id: 'white_circle', color: 'white', shape: 'circle',
    colorKor: '화이트', shapeKor: '동그라미', colorHex: '#F5F5F0', shapeSymbol: '○',
    energyTitle: '순수한 조화',
    psychologyFlow: '순수하고 맑은 에너지가 주변과 조화롭게 흐르고 있습니다. 새로운 시작과 순수한 연결을 원하는 마음이 흐르고 있습니다.',
    personalityFlow: '순수하고 진실한 성향입니다. 복잡한 것보다 단순하고 순수한 것을 추구하는 흐름이 있습니다.',
    emotionPattern: '감정이 맑고 순수하게 흐르는 패턴입니다. 복잡한 상황에서 단순함을 찾는 것이 도움이 됩니다.',
    strengths: ['순수함', '진실성', '새로운 시작', '조화'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '복잡한 것들을 내려놓고 순수하고 단순한 것에서 기쁨을 찾아보세요.',
    coachingMessage: '당신의 순수한 에너지가 주변을 맑게 합니다.\n그 순수함을 지켜가세요.',
  },
  {
    id: 'white_triangle', color: 'white', shape: 'triangle',
    colorKor: '화이트', shapeKor: '삼각형', colorHex: '#F5F5F0', shapeSymbol: '△',
    energyTitle: '순수한 성장 의지',
    psychologyFlow: '순수한 마음으로 성장하려는 에너지가 흐르고 있습니다. 아무것도 없는 깨끗한 상태에서 새롭게 시작하려는 의지가 활성화되어 있습니다.',
    personalityFlow: '순수하고 진실한 방식으로 성장하려는 성향입니다. 가식 없이 자신을 발전시키는 흐름이 있습니다.',
    emotionPattern: '순수한 의도로 시작하지만 현실의 복잡함에 상처받을 수 있는 패턴이 있습니다. 순수함을 지키면서도 현실적인 지혜를 함께 키워가는 것이 도움이 됩니다.',
    strengths: ['순수한 의도', '성장 의지', '진실성', '새로운 시작'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '순수한 의도를 지키면서도 현실적인 지혜를 함께 키워가보세요.',
    coachingMessage: '순수한 마음으로 성장하는 당신입니다.\n그 순수함과 함께 지혜도 함께 성장하고 있습니다.',
  },
  {
    id: 'white_inverted_triangle', color: 'white', shape: 'inverted_triangle',
    colorKor: '화이트', shapeKor: '역삼각형', colorHex: '#F5F5F0', shapeSymbol: '▽',
    energyTitle: '정화와 새로운 시작',
    psychologyFlow: '과거의 것들이 정화되고 새로운 시작을 위한 공간이 만들어지는 흐름입니다. 비워내고 새롭게 채우려는 내면의 움직임이 있습니다.',
    personalityFlow: '정화와 새로운 시작을 추구하는 성향입니다. 과거를 내려놓고 새롭게 시작하는 것에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '과거의 감정들을 정화하고 새롭게 시작하려는 패턴입니다. 충분히 정화한 후 새로운 시작을 맞이하는 것이 중요합니다.',
    strengths: ['정화력', '새로운 시작', '순수함', '회복력'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '과거의 것들을 충분히 정화하고, 새로운 시작을 위한 공간을 만들어보세요.',
    coachingMessage: '정화를 통해 새로운 시작을 준비하는 당신입니다.\n그 새로운 시작이 아름다울 것입니다.',
  },
  {
    id: 'white_square', color: 'white', shape: 'square',
    colorKor: '화이트', shapeKor: '네모', colorHex: '#F5F5F0', shapeSymbol: '□',
    energyTitle: '순수한 안정',
    psychologyFlow: '순수하고 깨끗한 안정감을 구축하려는 에너지가 흐르고 있습니다. 복잡함을 걷어내고 단순하고 안정적인 환경을 만들려는 마음이 흐르고 있습니다.',
    personalityFlow: '순수하고 안정적인 환경을 추구하는 성향입니다. 복잡한 것보다 단순하고 명확한 구조를 선호하는 흐름이 있습니다.',
    emotionPattern: '복잡한 상황에서 단순함을 찾으려는 패턴입니다. 필요한 복잡성도 수용하는 유연성이 도움이 됩니다.',
    strengths: ['순수함', '안정성', '단순함', '명확성'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '복잡한 것들을 정리하고 단순하고 안정적인 환경을 만들어보세요.',
    coachingMessage: '단순하고 순수한 안정을 추구하는 당신입니다.\n그 안정 속에서 충분히 쉬어가세요.',
  },
  {
    id: 'white_diamond', color: 'white', shape: 'diamond',
    colorKor: '화이트', shapeKor: '마름모', colorHex: '#F5F5F0', shapeSymbol: '◇',
    energyTitle: '순수한 유연성',
    psychologyFlow: '순수하고 맑은 에너지로 유연하게 변화를 수용하는 흐름입니다. 어떤 상황에서도 순수함을 잃지 않으면서 유연하게 적응하려는 흐름이 있습니다.',
    personalityFlow: '순수하고 유연한 성향입니다. 어떤 상황에서도 순수한 마음을 유지하는 흐름이 있습니다.',
    emotionPattern: '순수한 마음으로 변화를 수용하려는 패턴입니다. 때로는 현실적인 판단도 함께 하는 것이 도움이 됩니다.',
    strengths: ['순수함', '유연성', '적응력', '개방성'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '순수한 마음을 유지하면서도 현실적인 지혜를 함께 발휘해보세요.',
    coachingMessage: '순수하고 유연한 당신입니다.\n그 순수함이 당신의 가장 큰 강점입니다.',
  },
  {
    id: 'white_pentagon', color: 'white', shape: 'pentagon',
    colorKor: '화이트', shapeKor: '오각형', colorHex: '#F5F5F0', shapeSymbol: '⬠',
    energyTitle: '순수한 다방면 에너지',
    psychologyFlow: '순수한 에너지가 다양한 방향으로 흐르고 있습니다. 순수한 마음으로 다양한 것들을 탐구하고 경험하려는 흐름이 있습니다.',
    personalityFlow: '순수하고 다방면에 관심이 많은 성향입니다. 순수한 호기심으로 다양한 것들을 탐구하는 흐름이 있습니다.',
    emotionPattern: '순수한 호기심이 에너지를 분산시킬 수 있는 패턴입니다. 순수한 마음으로 하나에 집중하는 경험이 도움이 됩니다.',
    strengths: ['순수한 호기심', '다방면 관심', '개방성', '탐구심'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '순수한 호기심을 지금 가장 중요한 하나에 집중해보세요.',
    coachingMessage: '순수한 호기심이 당신을 풍요롭게 합니다.\n지금은 그 호기심을 하나에 집중할 시간입니다.',
  },
  {
    id: 'white_hexagon', color: 'white', shape: 'hexagon',
    colorKor: '화이트', shapeKor: '육각형', colorHex: '#F5F5F0', shapeSymbol: '⬡',
    energyTitle: '순수한 연결',
    psychologyFlow: '순수한 에너지가 다양한 연결을 통해 확장되는 흐름입니다. 순수한 마음으로 관계를 맺고 연결하려는 움직임이 있습니다.',
    personalityFlow: '순수하게 관계를 맺는 성향입니다. 진실하고 순수한 연결에서 에너지를 얻는 흐름이 있습니다.',
    emotionPattern: '순수한 연결을 원하지만 상처받을 수 있는 패턴이 있습니다. 순수함을 지키면서도 건강한 경계를 만드는 것이 도움이 됩니다.',
    strengths: ['순수한 연결', '진실성', '개방성', '따뜻함'],
    complementColors: ['블랙', '네이비'],
    recoveryDirection: '순수한 연결을 원하면서도 자신을 보호하는 건강한 경계를 만들어보세요.',
    coachingMessage: '순수하게 연결하는 당신의 마음이 아름답습니다.\n그 순수함을 지키면서도 자신을 돌봐주세요.',
  },

  // ─────────────────────────────────────────
  // 블랙 (BLACK) - 7장
  // ─────────────────────────────────────────
  {
    id: 'black_circle', color: 'black', shape: 'circle',
    colorKor: '블랙', shapeKor: '동그라미', colorHex: '#212121', shapeSymbol: '○',
    energyTitle: '깊은 포용과 내면 힘',
    psychologyFlow: '깊은 내면의 힘이 조용히 모든 것을 포용하는 흐름입니다. 강한 내면의 에너지가 안정적으로 흐르며 주변을 지탱하는 힘이 있습니다.',
    personalityFlow: '깊은 내면의 힘을 가진 성향입니다. 조용하지만 강한 에너지로 주변을 지탱하는 흐름이 있습니다.',
    emotionPattern: '감정을 깊이 내면에서 처리하는 패턴이 있습니다. 내면의 힘을 신뢰하면서도 외부와 소통하는 것이 도움이 됩니다.',
    strengths: ['깊은 내면 힘', '포용력', '안정감', '강인함'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '내면의 깊은 힘을 신뢰하고, 그 힘을 조금씩 외부로 표현해보세요.',
    coachingMessage: '당신 안에 깊은 힘이 있습니다.\n그 힘을 신뢰하고 세상과 나눠보세요.',
  },
  {
    id: 'black_triangle', color: 'black', shape: 'triangle',
    colorKor: '블랙', shapeKor: '삼각형', colorHex: '#212121', shapeSymbol: '△',
    energyTitle: '강한 내면 성장',
    psychologyFlow: '깊은 내면의 힘을 바탕으로 강하게 성장하려는 에너지가 흐르고 있습니다. 어떤 어려움도 극복하고 성장하려는 강한 의지가 활성화되어 있습니다.',
    personalityFlow: '강인하고 성장 지향적인 성향입니다. 어려움을 통해 더 강해지는 흐름이 있습니다.',
    emotionPattern: '강한 의지로 감정을 억누르는 패턴이 있을 수 있습니다. 강인함과 함께 감정을 인정하는 것이 더 건강한 성장을 이끕니다.',
    strengths: ['강인함', '성장 의지', '극복력', '깊은 힘'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '강인함과 함께 자신의 감정도 인정하고 돌보는 시간을 가져보세요.',
    coachingMessage: '강하게 성장하는 당신입니다.\n그 강인함 안에서 부드러움도 함께 키워가세요.',
  },
  {
    id: 'black_inverted_triangle', color: 'black', shape: 'inverted_triangle',
    colorKor: '블랙', shapeKor: '역삼각형', colorHex: '#212121', shapeSymbol: '▽',
    energyTitle: '깊은 내면 회복',
    psychologyFlow: '깊은 내면에서 조용히 회복이 이루어지는 흐름입니다. 오랫동안 쌓아온 무게들이 내면 깊이 흘러내려 정화되는 시기입니다.',
    personalityFlow: '깊은 내면 회복을 통해 성장하는 성향입니다. 혼자만의 깊은 시간에서 진정한 회복을 경험하는 흐름이 있습니다.',
    emotionPattern: '감정을 깊이 내면에서 처리하다 오랜 시간이 걸리는 패턴이 있습니다. 충분한 시간을 허용하면서도 조금씩 외부로 표현하는 것이 도움이 됩니다.',
    strengths: ['깊은 회복력', '내면 강인함', '자기 이해', '인내'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '깊은 내면 회복을 위한 충분한 시간과 공간을 자신에게 허용해보세요.',
    coachingMessage: '깊은 내면에서 회복이 일어나고 있습니다.\n그 과정에 충분한 시간을 허용해주세요.',
  },
  {
    id: 'black_square', color: 'black', shape: 'square',
    colorKor: '블랙', shapeKor: '네모', colorHex: '#212121', shapeSymbol: '□',
    energyTitle: '강한 안정과 기반',
    psychologyFlow: '강하고 안정적인 기반을 구축하려는 에너지가 흐르고 있습니다. 흔들리지 않는 안정적인 구조를 만들려는 강한 의지가 있습니다.',
    personalityFlow: '강하고 안정적인 성향입니다. 흔들리지 않는 기반을 만들고 지키는 것을 중요하게 여기는 흐름이 있습니다.',
    emotionPattern: '변화를 강하게 저항하는 패턴이 있을 수 있습니다. 안정적인 기반을 유지하면서도 필요한 변화를 수용하는 유연성이 도움이 됩니다.',
    strengths: ['강한 안정성', '기반 구축', '신뢰성', '강인함'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '강한 기반을 유지하면서도 필요한 변화를 수용하는 유연성을 키워보세요.',
    coachingMessage: '강한 기반이 있어 더 많은 것을 이룰 수 있습니다.\n그 기반 위에서 새로운 가능성도 탐색해보세요.',
  },
  {
    id: 'black_diamond', color: 'black', shape: 'diamond',
    colorKor: '블랙', shapeKor: '마름모', colorHex: '#212121', shapeSymbol: '◇',
    energyTitle: '강한 변화 수용',
    psychologyFlow: '깊은 내면의 힘을 바탕으로 변화를 수용하는 에너지가 흐르고 있습니다. 강인한 내면으로 어떤 변화도 수용하고 적응하려는 흐름이 있습니다.',
    personalityFlow: '강인하고 변화에 적응하는 성향입니다. 어떤 변화도 내면의 힘으로 수용하는 흐름이 있습니다.',
    emotionPattern: '변화를 강하게 수용하려다 내면의 감정을 억누르는 패턴이 있을 수 있습니다. 변화를 수용하면서도 감정을 인정하는 것이 중요합니다.',
    strengths: ['강인함', '변화 수용', '적응력', '깊은 힘'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '변화를 수용하면서도 그 과정에서 느끼는 감정도 충분히 인정해보세요.',
    coachingMessage: '강인하게 변화를 수용하는 당신입니다.\n그 과정에서 자신의 감정도 충분히 돌봐주세요.',
  },
  {
    id: 'black_pentagon', color: 'black', shape: 'pentagon',
    colorKor: '블랙', shapeKor: '오각형', colorHex: '#212121', shapeSymbol: '⬠',
    energyTitle: '다방면 내면 힘',
    psychologyFlow: '깊은 내면의 힘이 다양한 방향으로 발휘되는 흐름입니다. 다방면에서 강한 에너지를 발휘하려는 내면의 움직임이 활성화되어 있습니다.',
    personalityFlow: '다방면에서 강한 에너지를 발휘하는 성향입니다. 다양한 분야에서 깊은 힘을 발휘하는 흐름이 있습니다.',
    emotionPattern: '다방면으로 에너지를 발휘하다 소진될 수 있는 패턴이 있습니다. 에너지를 집중할 방향을 정하는 것이 도움이 됩니다.',
    strengths: ['다방면 강인함', '깊은 힘', '다재다능', '추진력'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '다방면의 에너지 중 지금 가장 중요한 방향에 집중해보세요.',
    coachingMessage: '다방면에서 강한 에너지를 발휘하는 당신입니다.\n지금은 가장 중요한 하나에 집중할 시간입니다.',
  },
  {
    id: 'black_hexagon', color: 'black', shape: 'hexagon',
    colorKor: '블랙', shapeKor: '육각형', colorHex: '#212121', shapeSymbol: '⬡',
    energyTitle: '강한 연결의 네트워크',
    psychologyFlow: '깊은 내면의 힘이 다양한 연결을 통해 확장되는 흐름입니다. 강한 에너지로 관계를 지탱하고 연결하려는 움직임이 있습니다.',
    personalityFlow: '강한 에너지로 관계를 지탱하는 성향입니다. 관계 속에서 깊은 힘을 발휘하는 흐름이 있습니다.',
    emotionPattern: '관계를 강하게 지탱하다 자신이 소진될 수 있는 패턴이 있습니다. 관계 속에서도 자신의 에너지를 지키는 것이 중요합니다.',
    strengths: ['강한 연결력', '관계 지탱', '신뢰성', '깊은 힘'],
    complementColors: ['화이트', '옐로우'],
    recoveryDirection: '관계를 지탱하면서도 자신의 에너지를 충분히 채우는 시간을 가져보세요.',
    coachingMessage: '강하게 관계를 지탱하는 당신입니다.\n그 힘의 원천인 자신도 충분히 돌봐주세요.',
  },
];

// 카드 ID로 데이터 조회
export function getCardById(id: string): CardData | undefined {
  return CARD_DATA.find(card => card.id === id);
}

// 컬러로 카드 목록 조회
export function getCardsByColor(color: CardColorType): CardData[] {
  return CARD_DATA.filter(card => card.color === color);
}

// 도형으로 카드 목록 조회
export function getCardsByShape(shape: ShapeType): CardData[] {
  return CARD_DATA.filter(card => card.shape === shape);
}

// 카드 위치별 해석 접두어
export const CARD_POSITION_LABELS = {
  1: { title: '무의식 / 내면 에너지', desc: '당신의 깊은 내면에서 흐르는 에너지' },
  2: { title: '현재 현실 에너지',     desc: '지금 현실에서 작동하는 에너지' },
  3: { title: '미래 / 회복 / 희망 에너지', desc: '앞으로 향하는 회복과 희망의 에너지' },
};
